[project]
name = "free-win-search"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Pedro", email = "87550035+odiseo0@users.noreply.github.com"},
]
dependencies = [
    "uvicorn[standard]==0.51.0",
    "fastapi[standard]==0.140.1",
    "SQLAlchemy==2.0.51",
    "pytest==9.1.1",
    "valkey==6.1.1",
    "beautifulsoup4>=4.15.0",
    "asyncpg>=0.31.0",
    "orjson>=3.11.9",
    "httpx>=0.28.1",
    "pydantic-settings>=2.12.0",
    "alembic>=1.17.2",
    "filelock>=3.20.3",
]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.basedpyright]
exclude = ["**/node_modules", "**/__pycache__", ".venv"]
typeCheckingMode = "basic"
reportUnnecessaryTypeIgnoreComment = true
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportReturnType = false
reportArgumentType = false

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
