"""changes

Revision ID: 820269ec1b4d
Revises: 0004_card_search
"""
from alembic import op
import sqlalchemy as sa


revision = '820269ec1b4d'
down_revision = '0004_card_search'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_listings', 'stock',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_listings', 'stock',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
